version: '3.7'

volumes:
  wordpress:
  driver: local
  driver_opts:
    type: none
    device: /home/wordpress
    o: bind
    mariadb:
  driver: local
  driver_opts:
    type: none
    device: /home/mariadb
    o: bind

services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress
    ports:
      - "80:80"
    
nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - wordpress:/var/www/html
    networks:
      - wordpress
    ports:
      - "8080:80"

networks:
  wordpress:
    driver: bridge

  